name: Android Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Make gradlew executable
      run: chmod +x gradlew
    - name: Build debug APK
      run: ./gradlew assembleDebug
    - name: Upload debug APK
      uses: actions/upload-artifact@v4
      with:
        name: subpilot-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
